### ISSUE TITLE
default database drop-down value

### ISSUE THREAD

**Issue by brillox** [gitsql/SQL-Server-Edition#10]
can I suggest that when in the software a user land on the window as per my screenshot below, it would be better that the drop-down with the database list would be either pre-populated with an item "please choose" so that the user can choose a database which trigger the object list. At the moment is pre-populated with the first database in the list but the object list does not refresh; therefore I have to choose the same database  in o
![image](https://cloud.githubusercontent.com/assets/685626/11767057/7b920526-a198-11e5-802c-e619b259e022.png)
rder to get the object list populated...

**Comment by anupsaund** [comment]
![capture](https://cloud.githubusercontent.com/assets/6728822/14066688/67f610cc-f448-11e5-98c5-3e4a60d6dbfb.PNG)

Label changed to "Database"

First option in the list is now, "Please Choose".

Selecting "Please Choose" has no UI change, 

@brillox  - Thanks for the great suggestion!

This is marked for the next release - which will be out once the CLI enhancement is complete.

**Comment by brillox** [comment]
thanks for the implementation!!  I will download the latest version.
