### ISSUE TITLE
SQL on Azure

### ISSUE THREAD

**Issue by jamesdecourcy** [gitsql/SQL-Server-Edition#12]
Does GitSQL work with an SQL DB on Azure?

I seem to be able to connect but the drop down where i select the database in step 2 is blank.

**Comment by anupsaund** [comment]
It may work if the database is created via gitsql import... Vs. Exporting from Azure where the DB has been created using the portal.

The tablespace is different in each case.

Which db tier are you using?

We can test it under the debugger?

**Comment by jamesdecourcy** [comment]
The DB was made using the portal and its on a Standard S0 tier

**Comment by anupsaund** [comment]
**Issue Overview**
gitSQL was unable to discover the Azure database list.

**Fix Details**
We made a change to the discovery method which now detects the databases over an azure connection.

**Additional Notes**

Database export required no additional code changes.
Database import required some work to pre-drop a database via the Import New option if it already exists.

Available in the next release 1.3.

**Comment by anupsaund** [comment]
@jamesdecourcy 

I have built a pre-release version available at http://www.gitsql.net/prerelease/setup.exe
