### ISSUE TITLE
FailedOperationException

### ISSUE THREAD

**Issue by dsonnet** [gitsql/SQL-Server-Edition#14]
Hi 

I encounter this error

Microsoft.SqlServer.Management.Smo.FailedOperationException: Script failed for StoredProcedure XXXXXXXX  ---> Microsoft.SqlServer.Management.Smo.PropertyCannotBeRetrievedException: Property TextHeader is not available for UserDefinedFunction 'YYYYYYY'. This property may not exist for this object, or may not be retrievable due to insufficient access rights.  The text is encrypted.

I run the gitsql with the Administrator rights

**Comment by anupsaund** [comment]
Hi @dsonnet - sorry you had this error.

Do you have the function declaration please?

I would like to run it under a debugger to see why it is failing.

**Comment by mariascott** [comment]
Hi @dsonnet - 

Is this issue still occurring for you?

**Comment by mariascott** [comment]
@dsonnet do let me know if this is still an issue.
