### ISSUE TITLE
Option to not include Dependencies

### ISSUE THREAD

**Issue by dmTech04** [gitsql/SQL-Server-Edition#15]
It would be great to expose an option in the UI to enable\disable scripting dependencies for objects.  I am scripting all tables, stored procedures, etc.  And for each stored procedure, it scripts all tables and UDF it depends on, and their recursive dependencies as well.

I can see that being really useful, but since I am doing all objects, it ends up making things slower and adds to the file sizes.  Having an option in the UI to disable this would be very helpful!

Thanks,
Keith

**Comment by anupsaund** [comment]
@dmTech04  Thank you for the great suggestion.

We have added a new "Options" item from the "Help" menu which shows a list of Export Options, as per screenshot below.

![newoptions](https://cloud.githubusercontent.com/assets/6728822/17085767/6d99924a-51d8-11e6-9e6e-13b849eb4db4.PNG)

This will be available in the next release. V 1.3

**Comment by dmTech04** [comment]
Awesome, that looks great!  Looking forward to it.  Thanks!

**Comment by dmTech04** [comment]
Hi Anup, I tried the v1.3 release and the option to not include dependencies works great!  It is so much faster to script our databases now!  :+1:   Thanks so much for adding this!
