### ISSUE TITLE
Selecting parent checkbox does not cause all children to be selected

### ISSUE THREAD

**Issue by christinaforney** [gitsql/SQL-Server-Edition#16]
When I select a parent level checkbox (e.g. Table, Stored Procedure, etc) I expect that all the children will also become selected. In our case, we want to select all stored procedures only. 

However, when I select the parent 'Stored Procedure' checkbox, it does not automatically select all children, and I am required to go through and select all children.
![image](https://cloud.githubusercontent.com/assets/1559622/18962775/0613b730-8627-11e6-8bf7-87c604785698.png)

**Comment by anupsaund** [comment]
Hi @christinaforney 

This is a new bug, that crept into the code base a few builds ago.

The code to handle the check box (and child selections) is in place but we accidentally knocked out the event handler on the check boxes.

We have placed it back in, with the view to release a hot fix soon, via a minor revision.

**Comment by christinaforney** [comment]
Awesome! Thanks for the update. Looking forward to the fix :)
