### ISSUE TITLE
Importing New DB with only Stored Procedures does not update Stored Procedures in SQL Server

### ISSUE THREAD

**Issue by christinaforney** [gitsql/SQL-Server-Edition#17]
I have a git repository of Stored Procedures only, and a SQL Server with Tables/Data and Stored Procedures. When I "Import New" Database from my git repository, I would expect that the Tables/Data are not touched, but all my Stored Procedures are dropped, and then imported from my git repo.

Currently, when I import new with this scenario, I am not seeing any changes to my Stored Procedures, nor the Tables/Data. (I would rather no changes than blowing out Tables/Data when that is unexpected).

**Comment by anupsaund** [comment]
**Updating Stored Procedures that already exist in a database**

Bug fix on #18 addresses this issue. 

The workflow in this scenario would be to select the stored procedures on screen 2.
This would limit the import on screen 3 to those selections.

**Import New - why does it delete everything?**

We designed it to perform a search on the source control directory on screen 3.
The user is presented with an option to select a database if multiples were found.
The user is then warned that an import will overwrite an existing database with the same name.

The idea was to select **Import New** when the database was not available in the drop down list and/or if it was already in the list but one wished to overwrite it with the source control copy.

^ Bug fix scheduled to next minor release.

**Comment by christinaforney** [comment]
Since this relies on #18, updating stored procedures will simply drop all, but will not actually import the ones from the git repository.
