### ISSUE TITLE
Importing individual stored procedures does not update SQL Server stored procedures

### ISSUE THREAD

**Issue by christinaforney** [gitsql/SQL-Server-Edition#18]
When I select a database, and select a specific stored procedure, choosing 'Import' as my option, the process runs on the selected stored procedure, but I am not seeing the update come through to my SQL Server that has tables/data and stored procedures in it.

For example, updating an existing stored procedure to have the changes from my git repository. I have not tested to see if the import works for a newly created stored procedure (though I don't think selection of procedures from a git repository is possible. I am guessing that for importing new, I will have to use the 'Import New' functionality instead.

**Comment by anupsaund** [comment]
BUG found which was preventing a drop of the stored procedure which resulted in a silent failure of the import.

Fixed and scheduled for next minor release.

**Comment by christinaforney** [comment]
This will now drop the stored procedure, but does not import the one from the git repository, so now I'm left with no stored procedure instead of an updated one in my SQL server.

**Comment by anupsaund** [comment]
Bug found and fixed - we need to perform some regression testing on associated areas of the workflow.

Scheduled for next release, although may come out sooner as a patch.
