### ISSUE TITLE
Display connected server name and selected DB in UI

### ISSUE THREAD

**Issue by christinaforney** [gitsql/SQL-Server-Edition#19]
Feature request: Would like to be able to see the server and DB I am currently working on somewhere at the top. This way I don't have to go all the way back to the first page of connection to see what I'm connected to (I often switch back and forth between test and production servers).

**Comment by anupsaund** [comment]
**Feature details**

i) Select a database on screen 2, screen 3 shows the database name.

![capture](https://cloud.githubusercontent.com/assets/6728822/19172999/c00e0136-8c1c-11e6-9c0c-b58e31f6e63a.PNG)

ii) Select **Import New**  on screen 2, the narrative on screen 3 remains as _Object list_ until a database is discovered. The UI is then updated to show which database is being processed.

Scheduled for release 1.3.1

**Comment by christinaforney** [comment]
Just getting around to reviewing - this correctly displays the database (very helpful!) but it doesn't show the server name. Would love to see that too!
