### ISSUE TITLE
no databases were found in the source control path

### ISSUE THREAD

**Issue by rbeck1947** [gitsql/SQL-Server-Edition#2]
After a longish period of initially reading the database, with one .NET crash, i was able to view four tables and four stored procedures.  I expected to see all the stored procedures but only able to select four of them.  

When i select one or more stored procedures, i could not click "export" and if i pressed run, after the warning message, i see this:  No Databases were found in the source control path which was provided.  The path is to a local folder on my workstation.  I understood that flat files (USP creation scripts) were to be created - and that doesn't require a database.  What am i not understanding?

**Comment by anupsaund** [comment]
Thank you for the feedback.

I had the same feedback regarding the 4 objects restrictions from several people.

The free product is currently limited to 4 objects, issue #1 has been raised to change the table limit to 20 and stored procedure limit to 10.

The 'No Databases were found in the source control path...' is shown when an import is performed.

Try unchecking the Import new check box on screen 2.

Also try select all. To see if all objects can initially be exported.

Do you have a screen shot regarding the .Net crash?

**Comment by rbeck1947** [comment]
Mr. Saund

Bingo!  (although i don't really understand now what 'Import New' does.)
 The stored procedures come over nicely into the newly created DB folder.

I don't have an issue with 'only four' since you probably want me to try it
out and buy the full version, however i would be happier if i saw all the
usps and could pick which ones i wanted to put into source control, up to a
maximum of four.

The .net crash message was not too informative, and i will try really hard
not to get another one, but if i do i'll screen shot the message.  The
first time i selected the database was painfully slow to interrogate the
database.  Subsequent loads are quiet rapid.

I am currently quite happy with your part of the procedure, but i am not a
GIT expert, as witnessed by the number of errors i get about' GET STATUS is
not a recognized verb'.  If i can get comfortable with GIT, i will get a
full licence of .gitSQL.

richard beck

**Comment by rbeck1947** [comment]
​
See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
Microsoft.SqlServer.Management.Common.ExecutionFailureException: An
exception occurred while executing a Transact-SQL statement or batch. --->
System.Data.SqlClient.SqlException: Timeout expired.  The timeout period
elapsed prior to completion of the operation or the server is not
responding. ---> System.ComponentModel.Win32Exception: The wait operation
timed out
   --- End of inner exception stack trace ---
   at
Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction
action, Object execObject, DataSet fillDataSet, Boolean catchException)
   at
Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteReader(String
sqlCommand, SqlCommand& command)
   --- End of inner exception stack trace ---
   at
Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteReader(String
sqlCommand, SqlCommand& command)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataReader(String
query, SqlCommand& command)
   at
Microsoft.SqlServer.Management.Smo.DataProvider.SetConnectionAndQuery(ExecuteSql
execSql, String query)
   at
Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataProvider(StringCollection
query, Object con, StatementBuilder sb, RetriveMode rm)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillData(ResultType
resultType, StringCollection sql, Object connectionInfo, StatementBuilder
sb)
   at
Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillDataWithUseFailure(SqlEnumResult
sqlresult, ResultType resultType)
   at
Microsoft.SqlServer.Management.Smo.SqlObjectBase.BuildResult(EnumResult
result)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.GetData(EnumResult
erParent)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData()
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData(Request
req, Object ci)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object
connectionInfo, Request request)
   at
Microsoft.SqlServer.Management.Smo.ExecutionManager.GetEnumeratorDataReader(Request
req)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitChildLevel(Urn
levelFilter, ScriptingOptions so, Boolean forScripting)
   at
Microsoft.SqlServer.Management.Smo.SmoCollectionBase.InitializeChildCollection(Boolean
refresh)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.GetEnumerator()
   at gitSQL.scripter.getObjects(String instanceName, String svrName,
Boolean loginSecure, String sqlServerLogin, String password, String dbName,
Boolean freeMode)
   at gitSQL.frmMain.cbxProject_SelectedIndexChanged(Object sender,
EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

gitSQL
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0

##     CodeBase: file:///C:/Program%20Files%20(x86)/gitSQL/gitSQL.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll

System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll

Microsoft.SqlServer.Smo
    Assembly Version: 10.0.0.0
    Win32 Version: 10.50.4000.0 ((KJ_PCU_Main).120628-0827 )
    CodeBase:

## file:///C:/Windows/assembly/GAC_MSIL/Microsoft.SqlServer.Smo/10.0.0.0__89845dcd8080cc91/Microsoft.SqlServer.Smo.dll

Microsoft.SqlServer.Management.Sdk.Sfc
    Assembly Version: 10.0.0.0
    Win32 Version: 10.50.4000.0 ((KJ_PCU_Main).120628-0827 )
    CodeBase:

## file:///C:/Windows/assembly/GAC_MSIL/Microsoft.SqlServer.Management.Sdk.Sfc/10.0.0.0__89845dcd8080cc91/Microsoft.SqlServer.Management.Sdk.Sfc.dll

Microsoft.SqlServer.ConnectionInfo
    Assembly Version: 10.0.0.0
    Win32 Version: 10.50.4000.0 ((KJ_PCU_Main).120628-0827 )
    CodeBase:

## file:///C:/Windows/assembly/GAC_MSIL/Microsoft.SqlServer.ConnectionInfo/10.0.0.0__89845dcd8080cc91/Microsoft.SqlServer.ConnectionInfo.dll

Microsoft.SqlServer.SqlEnum
    Assembly Version: 10.0.0.0
    Win32 Version: 10.50.4000.0 ((KJ_PCU_Main).120628-0827 )
    CodeBase:

## file:///C:/Windows/assembly/GAC_MSIL/Microsoft.SqlServer.SqlEnum/10.0.0.0__89845dcd8080cc91/Microsoft.SqlServer.SqlEnum.dll

Microsoft.SqlServer.SqlClrProvider
    Assembly Version: 10.0.0.0
    Win32 Version: 10.50.1600.1 ((KJ_RTM).100402-1539 )
    CodeBase:

## file:///C:/Windows/assembly/GAC_MSIL/Microsoft.SqlServer.SqlClrProvider/10.0.0.0__89845dcd8080cc91/Microsoft.SqlServer.SqlClrProvider.dll

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

Microsoft.SqlServer.Dmf
    Assembly Version: 10.0.0.0
    Win32 Version: 10.50.4000.0 ((KJ_PCU_Main).120628-0827 )
    CodeBase:

## file:///C:/Windows/assembly/GAC_MSIL/Microsoft.SqlServer.Dmf/10.0.0.0__89845dcd8080cc91/Microsoft.SqlServer.Dmf.dll

System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll

System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34244 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll

SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll

System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase:

## file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by anupsaund** [comment]
Hi Richard,

Thank you for the debug report.
It looks like fetching the objects from the database is timing out.

I will have to increase the timeout period to prevent the crash.

Timeout to be implemented...
_https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlcommand.commandtimeout.aspx_

**Comment by anupsaund** [comment]
Added to release v 1.0.1
