### ISSUE TITLE
Views not exporting

### ISSUE THREAD

**Issue by fred-m** [gitsql/SQL-Server-Edition#21]
My database has 84 views, only 68 of these were exported by gitsql.

All 84 showed up in the item select window.

Even when selecting a single one of the views that failed, nothing exports. I don't see any error message either.

It doesn't seem to be a permissions issue.

I'm happy to privately share the code of some of the missing views to see if there could be anything that is causing this

**Comment by mariascott** [comment]
Hi @fred-m 

Sorry to hear that you are having trouble - would you be able to download the latest version 1.4.0 to see if the issue occurs on that version?
