### ISSUE TITLE
Antivirus is blocking the download and install of gitsql

### ISSUE THREAD

**Issue by ericjuden** [gitsql/SQL-Server-Edition#23]
Hi, this issue is similar to this one: https://github.com/gitsql/SQL-Server-Edition/issues/13

We use Cylance and it's blocking me from downloading and installing the app.

https://www.virustotal.com/en/file/72dc881f9fb92a2ed0096f5eea61a3bb98782bb0f8f96c5551fb35f02a14a4f2/analysis/

Thanks,

Eric

**Comment by mariascott** [comment]
Hi @ericjuden ,

Thank you for getting in touch. 
We have raised a false positive report with Cylance.

I will give you an update in due course.

**Comment by ericjuden** [comment]
Thanks @mariascott. I'll keep an eye on this issue.

**Comment by mariascott** [comment]
@ericjuden - we had no feedback from Cylance regarding the false positive.

May I ask if you had any more issues since reporting this?

**Comment by ericjuden** [comment]
@mariascott, thanks for checking in. I just downloaded the setup file and attempted again. The installation process goes just fine. But the gitSQL.exe file is deleted before I can open the app. Attached is an image of what occurred immediately after the setup process.
![gitsql-error](https://user-images.githubusercontent.com/1031042/57480278-e1acb900-7264-11e9-9d3a-794d3f5d00da.png)

**Comment by mariascott** [comment]
Thank you @ericjuden 

I have submitted a new false positive report to them.

I guess it's a good sign that the installer completes. I have asked them to see if they can white list the executable.

**Comment by peteriburrows** [comment]
I am getting similar results from Windows Defender:
![image](https://user-images.githubusercontent.com/17571158/59359797-e9a9be00-8d26-11e9-9054-2b162b4fab84.png)

**Comment by mariascott** [comment]
Thank you @peteriburrows 

We have called in a security consultant to help and he has suggested we go down the code signing route to have our applications signed by a recognized authority.

Please bear with us whilst we re-package our applications.

All being well - we expect to be releasing signed versions for download by the end of July.

**Comment by mariascott** [comment]
@peteriburrows @ericjuden - We have successfully signed SQL Server Edition today and released it or download.

We submitted the file to virus total and the results look quite promising so far.

https://www.virustotal.com/gui/file/e34cccc347011855f9c63fcb9d0c6a69d936eeea62250a58d32bb754a40c27d0/detection

Would you give the latest installer a go and let us know what the experience is like?

**Comment by ericjuden** [comment]
@mariascott: I just downloaded version 1.4.5 (SQL Server edition) from your website and attempted to install. It was again quarantined.
![cylance-quarantine](https://user-images.githubusercontent.com/1031042/64187187-cbd78b00-ce35-11e9-8bb5-607cbe7ede05.png)

**Comment by mariascott** [comment]
We've improved the code signing on our latest version - 1.4.7 which has been analyzed over at https://www.virustotal.com/gui/file/f04cbf3e7eb06da781465c20743937302fbb8e8e0fac9852e90310751843609f/detection

We're hoping these incremental improvements reduce to eliminate these false positives.
