### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by edwardbrown** [gitsql/SQL-Server-Edition#25]
Just downloaded and installed gitSQL. After connecting to SQL Server, getting an error when trying to select a database.

[gitSQL error.txt](https://github.com/gitsql/SQL-Server-Edition/files/1992511/gitSQL.error.txt)

**Comment by mariascott** [comment]
Thanks for getting in touch.

May I get some more information please?

OS Version
SQL Server Version

**Comment by edwardbrown** [comment]
Thanks! 
OS Version Windows 10 Enterprise Version 1607 OS Build 14393.2125
SQL Server 12.0.5546

**Comment by mariascott** [comment]
The Issue has been found in the installer.

We are looking to release a new version this coming week to address the issue.

**Comment by edwardbrown** [comment]
Wonderful, thank you!

**Comment by jamesjburton** [comment]
The installer was installing gitSQL for SQL Server 2008?.. even though a newer version had been detected?!

Code refactored to install gitSQL against the correct SS ver.

Ready for QA. 👍

**Comment by davesinghs** [comment]
Passed 💯

**Comment by edwardbrown** [comment]
Wonderful! Thanks everybody.
