### ISSUE TITLE
Windows 10 update 1803 - Fails to check licence server

### ISSUE THREAD

**Issue by mariascott** [gitsql/SQL-Server-Edition#26]
This was reported by a gitSQL user and has been reproduced.

The issue has been caused by enhanced security which was introduced by Windows 10 update 1803.
A hot fix is to be released shortly to address the issue.

**How does the issue manifest?**

![capture](https://user-images.githubusercontent.com/23381132/40026719-6f835462-57ce-11e8-9c9a-f426fbccc093.PNG)

Entering a licence key will resolve the issue during that usage session.
Leaving the application and returning later will cause the same issue to manifest.

**Comment by jamesjburton** [comment]
Code refactored for enhanced security. 

Ready for QA. 👍

**Comment by davesinghs** [comment]
Passed 💯
