### ISSUE TITLE
User-Defined Types - not exporting

### ISSUE THREAD

**Issue by dazman66** [gitsql/SQL-Server-Edition#27]
Within a number of production databases we use both User-Defined Data Types and User-Defined Table Types.

It looks like both of these entity types are not exported via the GitSQL application either via GUI or Command line options.

Can these options be added to the application.

**Comment by dazman66** [comment]
Hi Maria,

Its been over 3 years, any news on this enhancement ?

If not; it really should be shown as a key lack of functionality within your [gitSQL vs Redgate](https://gitsql.net/gitsql_vs_redgate) web page.

Is there any ongoing development on the gitSQL package ?, as the latest available download as of now v1.4.6 is now over 2 years old, if you are not actively developing it any further, then I am quite willing to apply my skills in further enhancing the product !

**Comment by mariascott** [comment]
@dazman66 - we have built this into the next version, due for release within the next 7 days.

**Comment by mariascott** [comment]
@dazman66 - We've released this feature in 1.4.7.

Let us know how it goes.

**Comment by dazman66** [comment]
Hi Maria, that works just dandy, many thanks.
