### ISSUE TITLE
Command Line Options

### ISSUE THREAD

**Issue by anupsaund** [gitsql/SQL-Server-Edition#3]
### Command Line Options

This is for the licensed version.

Usage example to follow...

**Comment by anupsaund** [comment]
Development in progress.

Options File example to follow;

![command line options](https://cloud.githubusercontent.com/assets/6728822/14066541/0b62b5f8-f444-11e5-88c4-44c690124b9e.PNG)

**Comment by Jaxelr** [comment]
This looks awesome, any ETA on it?
