### ISSUE TITLE
can't import to sqlserver

### ISSUE THREAD

**Issue by setareiesabz** [gitsql/SQL-Server-Edition#32]
hi
I exported the schema from my database. After that, I changed a table and added a column for a test. I want to import the exported files to the database and remove all changed.
I imported that and finished importing without error, but my changes were not removed. 
What happened? Why my changes not been removed?
best wishes

**Comment by mariascott** [comment]
Hi @setareiesabz,

To confirm the steps.

1. Export database.
2. Created a new column in the database?
3. Import database.
4. The new column still exists, but should have been overwritten by the import?

May I ask what version of windows this is on?
What version of MS SQL Server is gitSQL connecting to?

**Comment by setareiesabz** [comment]
Your're right. Windows 10 and MSSql 2014.
