### ISSUE TITLE
free PostgreSQL Editio, didn't work correctly

### ISSUE THREAD

**Issue by setareiesabz** [gitsql/SQL-Server-Edition#33]
hi
I installed free PostgreSQL Edition and want to export the schema from my database for a test. After press, the button didn't finish the progressing.
I have pgsql 10.
what didn't work correctly?
best wishes

**Comment by mariascott** [comment]
Hi @setareiesabz - sorry to hear that this didn't work out for you.

Would you try exporting a database that has 1 table in it?
Does that export OK?
