### ISSUE TITLE
Sequences

### ISSUE THREAD

**Issue by B4PJS** [gitsql/SQL-Server-Edition#4]
Please can you add sequences to this tool?

**Comment by anupsaund** [comment]
Yes sure - I can add that in for you...

![11011608_10152803437806765_268725812104485701_n](https://cloud.githubusercontent.com/assets/6728822/7699056/3d7cf39c-fe0d-11e4-984c-c7aed1e95ea4.jpg)

I need to add some extra checks into the code base to only discover sequences if SQL Server 2012 or above is installed.

Are there any other objects that you would like discovering/scripting?

For example - Assemblies?

**Comment by anupsaund** [comment]
Sequences added as an object type for SQL Server 2012 and above.
