### ISSUE TITLE
Ignore Options

### ISSUE THREAD

**Issue by B4PJS** [gitsql/SQL-Server-Edition#5]
Please can you add an ignore option for sequences during deployment to ignore that start at value?

**Comment by anupsaund** [comment]
I'm thinking about adding this to a command line argument - see issue #3 for CLI enhancement.

The plan would to offer an Replace option which takes a filename as a parameter.

The file contents would then have;

line 1 - "string to find"
line 2 - "replace string"

Then it would be possible to replace a string with a blank line.

i.e.

line 1 "replace this line with nothing"
line 2 ""
line 3 "something else to replace"
line 4 "with this text this time"

The file contents could then be parsed with every SQL file that was exported using gitSQL as a post export parser before it is saved.
- N.B. there is a chance to separate the replace file into replace_sequences, replace_views, replace_tables - if you wish to target rules to a table. This may be more efficient in the long run.

Please add your comments if you think there is a better solution.
