### ISSUE TITLE
Installer files Corrupt

### ISSUE THREAD

**Issue by fergfamster** [gitsql/SQL-Server-Edition#8]
The downloaded installer from the site is getting corrupt files. Screen attached. this is a windows 8.1 pro N.

Thanks!
![error](https://cloud.githubusercontent.com/assets/709693/10673744/b1f6c690-78b4-11e5-87ec-10bbb9489235.png)

**Comment by anupsaund** [comment]
![testing](https://cloud.githubusercontent.com/assets/6728822/10687599/219bb0bc-7966-11e5-9539-44fd116c68f4.PNG)

**Comment by anupsaund** [comment]
Try temporarily disabling any resident anti-spyware/virus software before downloading.

Check your browser plugins for anything that may be blocking the download.
